# Generated by Django 3.1.3 on 2021-09-14 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0005_auto_20210913_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phoneNumber',
        ),
    ]
