# Generated by Django 3.1.3 on 2021-09-17 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0006_auto_20210914_0556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='location',
        ),
    ]
